In [243]:
import pandas as pd

# Load necessary data
df_recipes = pd.read_csv("CulinaryDB/01_Recipe_Details.csv")
df_ingredients = pd.read_csv("CulinaryDB/02_Ingredients.csv")
df_aliases = pd.read_csv("CulinaryDB/04_Recipe-Ingredients_Aliases.csv")

In [244]:
# Transform region to country, for simplicity some region and country of these region have not been added
region_country = {
    "Indian Subcontinent": ["India", "Pakistan", "Bangladesh", "Sri Lanka", "Nepal"],
    "East Asia": ["China", "Japan", "South Korea", "Mongolia", "Taiwan"],
    "Scandinavia": ["Sweden", "Norway", "Denmark", "Finland", "Iceland"],
    "South East Asia": ["Thailand", "Vietnam", "Malaysia", "Singapore", "Indonesia", "Philippines", "Cambodia", "Laos", "Myanmar", "Brunei"],
    "Middle East": ["Turkey", "Egypt", "Iran", "Iraq", "Israel", "Lebanon", "Jordan", "Syria", "Saudi Arabia", "United Arab Emirates",
                     "Qatar", "Kuwait", "Oman", "Yemen", "Palestine", "Bahrain"],
    "South America": ["Brazil", "Argentina", "Chile", "Peru", "Colombia", "Venezuela", "Ecuador", "Uruguay", "Paraguay", "Bolivia"],
    "Africa": ["Nigeria", "South Africa", "Morocco", "Ethiopia", "Kenya", "Ghana", "Egypt", "Algeria", "Tunisia", "Senegal", "Ivory Coast",
                "Cameroon", "Sudan", "Tanzania", "Uganda", "Libya", "Zimbabwe", "Angola", "Mozambique", "Namibia", "Botswana", "Zambia",
                  "Malawi", "Rwanda", "Burundi", "Sierra Leone", "Liberia", "Gambia", "Mauritania", "Chad", "Central African Republic",
                    "Congo", "Democratic Republic of the Congo", "Niger", "Mali", "Guinea", "Guinea Bissau", "Western Sahara", "South Sudan",
                      "Eritrea", "Somaliland", "Somalia", "South Sudan", "Gabon", "United Republic of Tanzania", "Madagascar"],
    "Caribbean": ["Cuba", "Jamaica", "Haiti", "Dominican Republic", "Trinidad and Tobago", "Barbados", "Bahamas", "Puerto Rico"],
    "Korea": ["South Korea", "North Korea"],
    "DACH Countries": ["Germany", "Austria", "Switzerland"],
    "British Isles": ["UK", "Ireland", "Scotland", "Wales"],
    "Eastern Europe": ["Poland", "Hungary", "Czech Republic", "Slovakia", "Ukraine", "Belarus", "Lithuania", "Latvia", "Estonia", "Russia", "Moldova", "Romania"],
}

def add_country(cuisine):
    if cuisine in region_country:
        return region_country[cuisine]
    else:
        return [cuisine]

df_recipes['Country'] = df_recipes['Cuisine'].apply(add_country)
df_recipes = df_recipes.explode('Country')

df_recipes.head(10)

,Recipe ID,Title,Source,Cuisine,Country
0,1,5 spice vegetable fried rice,TARLA_DALAL,Indian Subcontinent,India
0,1,5 spice vegetable fried rice,TARLA_DALAL,Indian Subcontinent,Pakistan
0,1,5 spice vegetable fried rice,TARLA_DALAL,Indian Subcontinent,Bangladesh
0,1,5 spice vegetable fried rice,TARLA_DALAL,Indian Subcontinent,Sri Lanka
0,1,5 spice vegetable fried rice,TARLA_DALAL,Indian Subcontinent,Nepal
1,2,aachar aaloo,TARLA_DALAL,Indian Subcontinent,India
1,2,aachar aaloo,TARLA_DALAL,Indian Subcontinent,Pakistan
1,2,aachar aaloo,TARLA_DALAL,Indian Subcontinent,Bangladesh
1,2,aachar aaloo,TARLA_DALAL,Indian Subcontinent,Sri Lanka
1,2,aachar aaloo,TARLA_DALAL,Indian Subcontinent,Nepal

In [245]:
# Standardize the column Aliased Ingredient Name to merge correctly
df_aliases['Aliased Ingredient Name'] = df_aliases['Aliased Ingredient Name'].str.strip().str.lower()
df_ingredients['Aliased Ingredient Name'] = df_ingredients['Aliased Ingredient Name'].str.strip().str.lower()

# Merge all csv together
df_merged = pd.merge(df_aliases, df_ingredients, on='Aliased Ingredient Name', how='left')

print(df_merged.shape)
df_merged.head(10)

(456562, 7)

,Recipe ID,Original Ingredient Name,Aliased Ingredient Name,Entity ID_x,Ingredient Synonyms,Entity ID_y,Category
0,1,capsicum,capsicum,362,capsicum; paprika; pepper-bell; pepper-sweet,362.0,Vegetable
1,1,green bell pepper,pepper bell,362,NaN,NaN,NaN
2,1,soy sauce,soy sauce,291,NaN,NaN,NaN
3,1,sunflower oil,sunflower,426,sunflower,426.0,Flower
4,2,buttermilk,buttermilk,61,buttermilk,61.0,Dairy
5,2,cumin,cumin,332,cumin; jeera,332.0,Spice
6,2,fenugreek,fenugreek,258,fenugreek; methi,258.0,Herb
7,2,ginger garlic paste,ginger garlic paste,2001,NaN,NaN,NaN
8,2,black mustard seed oil,mustard oil,317,mustard-oil,317.0,Plant
9,2,nigella seed,nigella seed,392,nigella-seed; kalonji,392.0,Nuts & Seed

In [246]:
df_merged = pd.merge(df_merged, df_recipes[['Recipe ID', 'Country']], on='Recipe ID', how='left')

print(df_merged.shape)
df_merged.head(10)

(1401487, 8)

,Recipe ID,Original Ingredient Name,Aliased Ingredient Name,Entity ID_x,Ingredient Synonyms,Entity ID_y,Category,Country
0,1,capsicum,capsicum,362,capsicum; paprika; pepper-bell; pepper-sweet,362.0,Vegetable,India
1,1,capsicum,capsicum,362,capsicum; paprika; pepper-bell; pepper-sweet,362.0,Vegetable,Pakistan
2,1,capsicum,capsicum,362,capsicum; paprika; pepper-bell; pepper-sweet,362.0,Vegetable,Bangladesh
3,1,capsicum,capsicum,362,capsicum; paprika; pepper-bell; pepper-sweet,362.0,Vegetable,Sri Lanka
4,1,capsicum,capsicum,362,capsicum; paprika; pepper-bell; pepper-sweet,362.0,Vegetable,Nepal
5,1,green bell pepper,pepper bell,362,NaN,NaN,NaN,India
6,1,green bell pepper,pepper bell,362,NaN,NaN,NaN,Pakistan
7,1,green bell pepper,pepper bell,362,NaN,NaN,NaN,Bangladesh
8,1,green bell pepper,pepper bell,362,NaN,NaN,NaN,Sri Lanka
9,1,green bell pepper,pepper bell,362,NaN,NaN,NaN,Nepal

In [247]:
# Keep only the necessary categories
categories = ['Meat', 'Fish', 'Vegetable', 'Fruit', 'Beverage', 'Bakery']
df_filtered = df_merged[df_merged['Category'].isin(categories)]

# Drop all ligne with wrong categories or non relevant ingredients
df_filtered = df_filtered[~df_filtered['Aliased Ingredient Name'].str.contains('fish')]
df_filtered = df_filtered[~df_filtered['Aliased Ingredient Name'].str.contains('onion')]
df_filtered = df_filtered[~df_filtered['Aliased Ingredient Name'].str.contains('egg')]

print(df_filtered.shape)
df_filtered.head(10)

(280485, 8)

,Recipe ID,Original Ingredient Name,Aliased Ingredient Name,Entity ID_x,Ingredient Synonyms,Entity ID_y,Category,Country
0,1,capsicum,capsicum,362,capsicum; paprika; pepper-bell; pepper-sweet,362.0,Vegetable,India
1,1,capsicum,capsicum,362,capsicum; paprika; pepper-bell; pepper-sweet,362.0,Vegetable,Pakistan
2,1,capsicum,capsicum,362,capsicum; paprika; pepper-bell; pepper-sweet,362.0,Vegetable,Bangladesh
3,1,capsicum,capsicum,362,capsicum; paprika; pepper-bell; pepper-sweet,362.0,Vegetable,Sri Lanka
4,1,capsicum,capsicum,362,capsicum; paprika; pepper-bell; pepper-sweet,362.0,Vegetable,Nepal
55,2,potato,potato,373,potato,373.0,Vegetable,India
56,2,potato,potato,373,potato,373.0,Vegetable,Pakistan
57,2,potato,potato,373,potato,373.0,Vegetable,Bangladesh
58,2,potato,potato,373,potato,373.0,Vegetable,Sri Lanka
59,2,potato,potato,373,potato,373.0,Vegetable,Nepal

In [248]:
ingredient_counts = df_filtered.groupby(['Country', 'Category', 'Aliased Ingredient Name']).size().reset_index(name='Count')

# For each country and category, pick the ingredient with the highest count
top_ingredients = ingredient_counts.loc[ingredient_counts.groupby(['Country', 'Category'])['Count'].idxmax()]

# Create needead format for worldMap.js
df_clean = top_ingredients.pivot(index='Country', columns='Category', values='Aliased Ingredient Name').reset_index()

In [249]:
# Save CSV file
df_clean.to_csv("CulinaryDB/data_world_map.csv", index=False)

In [250]:
# Correct the header of the file to lowercase
input_path = "CulinaryDB/data_world_map.csv"

with open(input_path, "r", encoding="utf-8") as infile:
    lines = infile.readlines()

lines[0] = lines[0].strip().lower() + "\n"

with open(input_path, "w", encoding="utf-8") as outfile:
    outfile.writelines(lines)